server.port=8080

# MySQL Database Config
spring.datasource.url=jdbc:mysql://localhost:3306/talentfit_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Harsh@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings (Automatic table generator)

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Gemini AI API Configuration
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
gemini.api.key=AQ.Ab8RN6J00rQpssHD2dBQSP9C88_3yOoQacVWIu6VkBTA-7S6fw
